INSERT INTO currencies (code, name, symbol, minor_units) VALUES
  ('EUR', 'Euro', '€', 2),
  ('USD', 'US Dollar', '$', 2),
  ('GBP', 'Pound Sterling', '£', 2),
  ('BRL', 'Brazilian Real', 'R$', 2),
  ('JPY', 'Japanese Yen', '¥', 0),
  ('AED', 'UAE Dirham', 'د.إ', 2),
  ('MAD', 'Moroccan Dirham', 'د.م.', 2),
  ('CHF', 'Swiss Franc', 'CHF', 2),
  ('SEK', 'Swedish Krona', 'kr', 2),
  ('NOK', 'Norwegian Krone', 'kr', 2),
  ('DKK', 'Danish Krone', 'kr', 2),
  ('PLN', 'Polish Zloty', 'zł', 2),
  ('CZK', 'Czech Koruna', 'Kč', 2),
  ('HUF', 'Hungarian Forint', 'Ft', 2),
  ('TRY', 'Turkish Lira', '₺', 2),
  ('ZAR', 'South African Rand', 'R', 2),
  ('AUD', 'Australian Dollar', 'A$', 2),
  ('CAD', 'Canadian Dollar', 'C$', 2),
  ('MXN', 'Mexican Peso', '$', 2),
  ('INR', 'Indian Rupee', '₹', 2)
ON CONFLICT (code) DO NOTHING;
